Added Multiple Configuration sources!

diff --git a/zmux b/zmux
--- a/zmux
+++ b/zmux
@@ -2,7 +2,7 @@
 # A script to manage and create Tmux Session.
 
 set -euo pipefail
-CONFIG_DIR="${HOME}/.config/zmux/"
+CONFIG_DIR="${HOME}/.config/zmux"
 CONFIG_FILE="${HOME}/.config/zmux/config.yaml"
 FZF=""
 
@@ -33,25 +33,34 @@ session_exists() {
 }
 
 check_config() {
-    if [[ -f "${CONFIG_FILE}" ]]; then
-        if [[ $(yq ${CONFIG_FILE} 2>/dev/null) ]]; then
-            configured=$(yq '.sessions | keys' "${CONFIG_FILE}" 2>/dev/null | sed 's/- //')
-        else
-            echo "zmux: Error: Config file not valid" >&2;
-            exit 2;
-        fi
-    else
-        echo "zmux: Error: Config file not found at '${CONFIG_FILE}'" >&2
-        read -p "Want to create Config file?[Y/n] " yn
+    if [[ ! -d "${CONFIG_DIR}" ]]; then
+        echo "zmux: Error: Config directory not foundat '${CONFIG_FILE}'" >&2
+        read -p "Want to create Config Directory?[Y/n] " yn
         case $yn in
-            [Yy]* ) 
-                mkdir -p "${CONFIG_DIR}" && touch "${CONFIG_FILE}";
-                echo "Config file created at '${CONFIG_FILE}'"
+            [Yy]* )
+                mkdir -p "${CONFIG_DIR}" && echo "Config directory created at '${CONFIG_DIR}'";
+                touch "${CONFIG_FILE}" && echo "Default config file created at '${CONFIG_FILE}'";
                 exit 0;;
-            [Nn]* ) exit ;;
+            [Nn]* )
+                echo "zmux: Error: Need to have Config directory";
+                exit 1;;
         esac;
         exit 2;
     fi
+    yaml_files=("${CONFIG_DIR}"/*.yaml)
+    if [[ ! -e "${yaml_files[0]}" ]]; then
+        echo "zmux: Error: No yaml configuration found in '${CONFIG_DIR}'";
+        exit 1;
+    fi
+    configured=""
+    for config_file in "${CONFIG_DIR}"/*.yaml; do
+        if [[ -f "${config_file}" ]]; then
+            if [[ $(yq '.sessions' "${config_file}"  | grep -v null) ]]; then
+                file_sessions=$(yq '.sessions | keys' "${config_file}" | sed 's/- //')
+                configured+="${file_sessions}"$'\n'
+            fi
+        fi
+    done
 }
 
 export FZF_DEFAULT_OPTS=" --tmux 70% \
@@ -79,15 +88,29 @@ list_sessions() {
 
 create_session() {
     local session_name="$1"
-    local root_dir=$(eval echo $(yq ".sessions.${session_name}.root" "$CONFIG_FILE"))
-    local start_index=$(yq ".sessions.${session_name}.start_index // 1" "$CONFIG_FILE")
+    local config_file=""
+
+    for yaml_file in "${CONFIG_DIR}"/*.yaml; do
+        if yq ".sessions.${session_name}" "${yaml_file}" | grep -v null &>/dev/null ; then
+            config_file="${yaml_file}"
+            break
+        fi
+    done
+
+    if [[ -z $config_file ]]; then
+        echo "zmux: Error: Session '${session_name}' not found in any config file."
+        exit 2;
+    fi
+
+    local root_dir=$(eval echo $(yq ".sessions.${session_name}.root" "$config_file"))
+    local start_index=$(yq ".sessions.${session_name}.start_index // 1" "$config_file")
 
     tmux new-session -d -s $session_name -c $root_dir
 
-    local window_count=$(yq ".sessions.${session_name}.windows | length" "$CONFIG_FILE")
+    local window_count=$(yq ".sessions.${session_name}.windows | length" "$config_file")
     for ((i = 0; i < window_count; i++)); do
-        local window_name=$(yq ".sessions.${session_name}.windows[${i}].name" "$CONFIG_FILE")
-        local window_command=$(yq ".sessions.${session_name}.windows[${i}].command" "$CONFIG_FILE")
+        local window_name=$(yq ".sessions.${session_name}.windows[${i}].name" "$config_file")
+        local window_command=$(yq ".sessions.${session_name}.windows[${i}].command" "$config_file")
         if ((i == 0)); then
             tmux rename-window -t ${session_name}:${start_index} $window_name
         else
@@ -102,6 +125,24 @@ create_session() {
 # When using -e flag
 export_config() {
     local session_name=$(tmux display-message -p "#S")
+
+    echo "Avaiable config files:"
+    find ${CONFIG_DIR} -type f -name "*.yaml" -exec basename '{}' .yaml \;
+    read -p "Enter file (without path or extension) to export to: " config_name
+    if [[ -z "${config_name}" ]]; then
+        config_name="${session_name}.yaml"
+    fi
+    if [[ ! "$config_name" =~ \.yaml$ ]]; then
+        config_name="${config_name}.yaml"
+    fi
+    local count=1
+    local base_config="${config_name}"
+    while [[ -f "${CONFIG_DIR}/${config_name}" ]]; do
+        name="${base_config%.*}"
+        config_name="${name}_${count}.yaml"
+        ((count++))
+    done
+    local export_file="${CONFIG_DIR}/${config_name}"
     local root_dir=$(tmux display-message -p -t $session_name:1 '#{pane_current_path}')
     if [[ -z "${root_dir}" ]]; then
         read -p "zmux: Error: Root not set, please type root path :" answer
@@ -123,7 +164,8 @@ export_config() {
         - name: $name
           command: \"$last_command\""
     done <<< "$windows"
-    echo -e "${yaml_content}" >> $CONFIG_FILE;
+    echo -e "${yaml_content}" >> $export_file;
+    echo "Created config file for '${session_name}' on '${export_file}'"
 }
 
 # When using -h flag
