Release 0.1.1 version. Bugfixes

diff --git a/zmux b/zmux
--- a/zmux
+++ b/zmux
@@ -1,20 +1,27 @@
 #!/usr/bin/env bash
 
 set -eu
-CONFIG_FILE="${HOME}/.config/zmux/config.yaml"
+CONFIG_FILE="${HOME}/.config/ezmux/config.yaml"
 
-#Check requirements
-command -v yq >/dev/null 2>&1 || { echo "Error: yq is required but not installed."; exit 1; }
 command -v tmux >/dev/null 2>&1 || { echo "Error: tmux is required but not installed."; exit 1; }
 command -v fzf >/dev/null 2>&1 || { echo "Error: fzf is required but not installed."; exit 1; }
 
+command -v yq >/dev/null 2>&1 || { echo "Error: yq is required but not installed."; exit 1; }
+yq_version=$(yq --version | awk '{print $4}')
+if [ "$yq_version" \< "v4.44.6" ]; then
+    echo "Error: yq version must be greater of equal than v4.44.6"
+    echo "Error: Current version is ${yq_version}"
+    exit 1;
+fi;
+
 list_sessions() {
     if [[ -f "$CONFIG_FILE" ]]; then
-        configured=$(yq '.sessions | keys' "$CONFIG_FILE" 2>/dev/null  | grep -v '\[\|\]' | sed 's/,//' | sed 's/^  //' | sed 's/"//g')
+        configured=$(yq '.sessions | keys' "$CONFIG_FILE" 2>/dev/null \
+            | sed 's/- //')
     else
         echo "  Config file not found at $CONFIG_FILE"
     fi
-    active=$(tmux ls -F "#S" 2>/dev/null)
+    active=$(tmux ls -F "#S" 2>/dev/null | echo "")
     combined=$(printf "%s\n%s" "$configured" "$active" | sort -u)
     local session=$(echo "$combined" | fzf --tmux 70%)
     if [[ -n "$session" ]]; then
@@ -29,21 +36,9 @@ list_sessions() {
     fi
 }
 
-## This is for fallback
-# list_sessions() {
-#     # echo "Available Sessions:"
-#     echo "Configured Sessions:"
-#
-#     # Safely list configured sessions
-#     if [ -f "$CONFIG_FILE" ]; then
-#         yq '.sessions | keys' "$CONFIG_FILE" 2>/dev/null  | grep -v '\[\|\]' | sed 's/,//' | sed 's/^  //' | sed 's/"//g' || echo "  No configured sessions found"
-#     else
-#         echo "  Config file not found at $CONFIG_FILE"
-#     fi
-#
-#     echo -e "Active Tmux Sessions:"
-#     tmux list-sessions 2>/dev/null | sed 's/^  //' | cut -f 1 -d ':' || echo "  No active sessions"
-# }
+tmux_running() {
+    tmux ls > /dev/null 2>&1
+}
 
 session_exists() {
     tmux has-session -t "$1" 2>/dev/null
@@ -51,15 +46,15 @@ session_exists() {
 
 create_session() {
     local session_name="$1"
-    local root_dir=$(yq ".sessions.${session_name}.root" "$CONFIG_FILE")
+    local root_dir=$(eval echo $(yq ".sessions.${session_name}.root" "$CONFIG_FILE"))
     local start_index=$(yq ".sessions.${session_name}.start_index // 1" "$CONFIG_FILE")
 
     tmux new-session -d -s $session_name -c $root_dir
 
     local window_count=$(yq ".sessions.${session_name}.windows | length" "$CONFIG_FILE")
     for ((i=0; i<window_count; i++)); do
-        local window_name=$(yq ".sessions.${session_name}.windows[${i}].name" "$CONFIG_FILE" | sed 's/"//g')
-        local window_command=$(yq ".sessions.${session_name}.windows[${i}].command" "$CONFIG_FILE"| sed 's/"//g')
+        local window_name=$(yq ".sessions.${session_name}.windows[${i}].name" "$CONFIG_FILE")
+        local window_command=$(yq ".sessions.${session_name}.windows[${i}].command" "$CONFIG_FILE")
         if ((i == 0)); then
             tmux rename-window -t ${session_name}:${start_index} $window_name
         else
@@ -70,16 +65,25 @@ create_session() {
         fi
     done
 }
+
 ## Main Program
+main() {
+
 if [[ $# -eq 0 ]]; then
     list_sessions
     exit 0
 fi
 
-session_name="$1"
-if ! yq ".sessions.${session_name}" "$CONFIG_FILE" > /dev/null 2>&1; then
-    echo "Error: Session '${session_name}' not found in configuration."
+local session_name="$1"
+
+if (! yq ".sessions.${session_name}" "$CONFIG_FILE" &> /dev/null && ! session_exists $1) ; then
+    echo "Error: Session '${session_name}' not found."
     exit 1
+fi
+
+if ! tmux_running; then
+    echo "No Tmux server found, starting default server"
+    tmux new-session -d -s default
 fi
 
 if ! session_exists "$session_name"; then
@@ -91,4 +95,6 @@ if [[ -z "${TMUX:-}" ]]; then
 else
     tmux switch-client -t "$session_name"
 fi
-fi
+}
+
+main "$@"
